name: SBOM Generation

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      # Install Syft (free & open source)
      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh \
            | sh -s -- -b /usr/local/bin

      # Generate SBOM in CycloneDX JSON format
      - name: Generate SBOM
        run: |
          syft dir:. -o cyclonedx-json > sbom.json

      # Save SBOM as a pipeline artifact
      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json
